
apiVersion: apps/v1
kind: Deployment

metadata:
  name: snaji-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: snaji-api

  template:
    metadata:
      labels:
        app: snaji-api

    spec:
      containers:
        - name: api
          image: snaji/api:v9

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
